apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: chat
  labels:
    zsoo-app: chat-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      zsoo-app: chat-zookeeper
  template:
    metadata:
      labels:
        zsoo-app: chat-zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          env:
            - name: ZOO_SERVER_ID
              value: "1"
            - name: ZOO_SERVERS
              value: 0.0.0.0:2888:3888
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: chat
  labels:
    zsoo-app: chat-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      zsoo-app: chat-kafka
  template:
    metadata:
      labels:
        zsoo-app: chat-kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://127.0.0.1:9092
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: chat
spec:
  ports:
    - name: zookeeper
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: p2888
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: p3888
      protocol: TCP
      port: 3888
      targetPort: 3888
  selector:
    zsoo-app: chat-zookeeper
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: chat
spec:
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    zsoo-app: chat-kafka
  type: ClusterIP
